In [ ]:
!pwd

In [1]:
import numpy as np

In [2]:
with open("Data/02a.txt", "r") as input:
    data = input.readlines()
data[0:5]

['8 10 13 14 12\n',
 '40 42 45 47 49 49\n',
 '45 48 51 52 55 58 62\n',
 '61 63 64 67 69 72 74 81\n',
 '95 97 98 99 98 99\n']

In [3]:
def get_ints(s):
    i = s.split()
    return np.array(list(map(int, i)))

In [4]:
reports = list(map(get_ints, data))
reports[0:5]

[array([ 8, 10, 13, 14, 12]),
 array([40, 42, 45, 47, 49, 49]),
 array([45, 48, 51, 52, 55, 58, 62]),
 array([61, 63, 64, 67, 69, 72, 74, 81]),
 array([95, 97, 98, 99, 98, 99])]

In [7]:
def is_safe(report):
    d = report[1:] - report[:-1]
    report_min = min(d)
    report_max = max(d)
    if report_min * report_max <= 0:
        return False
    if report_min > 0:
        return report_min >= 1 and report_max <= 3
    return report_max <= -1 and report_min >= -3


In [8]:
safe_reports = [ report for report in reports if is_safe(report)]

In [9]:
len(safe_reports)

598