In [1]:
!pwd

/private/var/mobile/Containers/Shared/AppGroup/F82BEA26-21DA-4B80-8660-E4843E122113/File Provider Storage/Repositories/Aoc24


In [2]:
import numpy as np

In [3]:
with open("Data/01a.txt", "r") as input:
    data = input.readlines()
data[0:5]

['15131   78158\n',
 '32438   35057\n',
 '12503   57702\n',
 '73808   43128\n',
 '57168   71761\n']

In [4]:
def get_ints(s):
    i = s.split()
    return list(map(int, i))

In [5]:
data = np.array(list(map(get_ints, data)))
data[0:5]

array([[15131, 78158],
       [32438, 35057],
       [12503, 57702],
       [73808, 43128],
       [57168, 71761]])

In [6]:
data = np.transpose(data)
len(data)

2

In [7]:
r0 = np.array(sorted(data[0]))

In [8]:
r0[0:5]

array([10024, 10426, 10487, 10622, 10796])

In [9]:
r1 = np.array(sorted(data[1]))

In [10]:
r1[0:5]

array([10005, 10083, 10380, 10668, 10908])

In [20]:
k0 = k1 = 0
n = len(r0)
res = 0

In [21]:
while k0 < n and k1 < n:
    if r0[k0] < r1[k1]:
        k0 += 1
    elif r0[k0] > r1[k1]:
        k1 += 1
    else:
        x = r0[k0]
        p0 = p1 = 0
        while k0 < n and r0[k0] == x:
            p0 += 1
            k0 += 1
        while k1 < n and r1[k1] == x:
            p1 += 1
            k1 += 1
        res += p0 * p1 * x
res, k0, k1

(21271939, 1000, 997)